---
# tasks file for roles/ubuntu-ftp
- name: install vsftpd ubuntu
  apt:
    name: vsftpd
    state: latest
    update_cache: yes

- name: disable firewall
  service:
    name: ufw
    state: stopped
    enabled: no

- name: create ftp user
  user:
    name: choong
    password: chottt123
    comment: "FTP user successfully created"

- name: create ftp dir
  file:
    path: /home/choong/ftp
    state: directory
    owner: choong
    group: choong
    mode: '0555'

- name: create ftp files
  file:
    path: /home/choong/ftp/files
    state: directory
    owner: choong
    group: choong

- name: copy vsftpd.config
  copy:
    src: vsftpd.conf
    dest: /etc/vsftpd.conf
  register: vsftpd_config

- name: restart vsftpd.config
  service:
    name: vsftpd
    state: restarted
  when: vsftpd_config.changed
